---
- hosts: linux
  become: true
  tasks: 
  - name: Install apache on ubuntu
    apt:
      name: apache2
      update_cache: true
      state: latest
    when: ansible_os_family == "Debian"
  - name: Start apache on ubuntu
    service: 
      name: apache2
      enabled: true
      state: started
    when: ansible_os_family == "Debian"
  - name: Install apache on centos
    yum:
      name: httpd
      update_cache: true
      state: latest
    when: ansible_os_family == "RedHat"
  - name: Start apache on centos
    service: 
      name: httpd
      enabled: true
      state: started
    when: ansible_os_family == "RedHat"
  - name: create index file using template on ubuntu
    template: 
      src: /root/playbooks/index.html.j2
      dest: /var/www/html/index.html
    notify: restart apache2
    when: ansible_os_family == "Debian"
  - name: create index file using template on centos
    template: 
      src: /root/playbooks/index.html.j2
      dest: /var/www/html/index.html
    notify: restart httpd
    when: ansible_os_family == "RedHat"
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart httpd
      service: name=httpd state=restarted
