---
- hosts: centos
  become: true
  tasks:
  - name: create fact directory
    file:
      path: /etc/ansible/facts.d
      recurse: true
      state: directory

  - name: create fact script using template
    template:
      src: /root/playbooks/datetime.sh.j2
      dest: /etc/ansible/facts.d/date_time.fact
      mode: 0755
 
  - name: reload ansible facts
    setup:
       filter: ansible_local
 
  - name: print local facts
    debug: 
      msg: "custom fact is {{ ansible_local.date_time }}"
      
