---
- hosts: linux
  tasks:
  - name: Create file
    file:
      path: /home/ansible/testfile
      state: touch
  - name: Create directory
    file:
      path: /home/ansible/testdir
      state: directory
