---
- hosts: centos
  become: true
  tasks: 
  - name: Install mariadb server
    yum:
      name: mariadb-server
      state: latest
    tags:
    - install
  - name: start mariadb
    service: 
      name: mariadb
      state: started
    tags:
    - start 
  - name: create user
    user:
      name: testuser
