---
- hosts: linux
  vars:
    test: welcome to training
    Test: Testing case sensitivity
    
  tasks: 
  - name: print variable
    debug:
      msg="{{ test }}"
  - name: print another variable
    debug:
      msg="{{ Test }}"
